### ISSUE TITLE
Implement conditioning on variants

### ISSUE THREAD

**Issue by welchr** [statgen/raremetal.js#13]
## Summary

Implement support for conditioning on one or multiple variants and adjusting the score statistics, covariance matrix, p-values, etc. accordingly. 

Adjusted score statistics/covariance can then be used downstream for aggregation tests.

## Method

<img src="https://user-images.githubusercontent.com/165778/91375112-cc57f700-e7e7-11ea-9cdc-fc1538d3bb52.png" width=700/>

## Existing code

RAREMETAL conditions on variants in this code: 

https://github.com/statgen/raremetal/blob/2c82cfc5710dbd9fd56ef67a7ca5f74772d4e70d/raremetal/src/Meta.cpp#L2093-L2144

## Papers

The supplementary PDF for Dajiang's paper is useful to read:

Liu DJ, Peloso GM, Zhan X, Holmen OL, Zawistowski M, Feng S, et al. Meta-analysis of gene-level tests for rare variant association. Nat Genet. 2014;46: 200–204.

Feng S, Liu D, Zhan X, Wing MK, Abecasis GR. RAREMETAL: fast and powerful meta-analysis for rare variants. Bioinformatics. 2014;30: 2828–2829.

## Tasks

- [ ] Implement method above
- [ ] Modify CLI to take in a list of variants to condition on (useful for testing)
- [ ] Test implementation against existing software (raremetal, rvtest, R, etc.)
- [ ] Write unit tests covering various situations (e.g. condition on 1 variant, >1 variant, ill conditioned matrix, etc.)
- [ ] Write docs
- [ ] Comment all code
